### ISSUE TITLE
how to deal with mixed datasets?

### ISSUE THREAD

**Issue by brandonjnelsonFDA** [bnel1201/PedSilicoICH#20]
We have introduced notebooks for dealing with both MIDA and NIHPD heads as base models to add lesions to, but do we want to mix them together in the same resulting dataset?

I explored this in a recent commit to my developement branch, one issue I noticed is that they are different sizes, so one step may be to resample them such that they are a common size. That is if we agree it makes sense to mix them. @jmweaver-FDA , what do you think, should we mix MIDA and NIHPD and potentially other data sources together in the final dataset? I think we should at least provide options to mix or select which to include, but that's just my opinion here.

![image](https://github.com/user-attachments/assets/21eea776-288b-41c6-91dc-34eec3aff3ed)

In this commit 17a81f5b73446605b577e62b7086271faad042ee I added classes to make each dataset easier to load and have a consistent signature:

https://github.com/brandonjnelsonFDA/PedSilicoICH/blob/17a81f5b73446605b577e62b7086271faad042ee/src/pedsilicoICH/ground_truth_definition/phantoms.py#L68

**Comment by jmweaver-FDA** [comment]
I think making the assumption that the final dataset will have both is a good thing to do moving forward, because it'd be easier to remove them from the dataset after the fact than re-code things to be compatible with them in the future - I've already done this with my epidural/subdural lesion insertion code.

As for the sizes, I think having the ground truth phantom in a common resolution is a good move and would be easy to implement. Obviously, the final resolution of the reconstructed CT images could vary (and probably should to ensure dataset heterogeneity). If needed, we should be able to upsample the NIHPD phantom with ease as well.

**Comment by brandonjnelsonFDA** [comment]
great thank you for the feedback, I agree as long as we make that clear in the metadata it'll be easy to filter by dataset if anyone doesn't want the mix.

As for resizing to a consistent size, monai makes that pretty straightforward, just added it to my dev branch and can merge to main soon: https://github.com/brandonjnelsonFDA/PedSilicoICH/blob/c41e33483c890c97f2622a3f2ace46b7bea73e33/CT_dataset_pipeline.py#L69

**Comment by brandonjnelsonFDA** [comment]
Let's close this issue for now then, I just added a recommended scan range feature which adjust the z range based on the scout image, this avoids scanning too much air or exceeding the allowable scan range for different size (in mm) patients since z range must be specified in mm

https://github.com/brandonjnelsonFDA/PedSilicoICH/blob/af8e0cf1d33cde3fa20ed7516457fa1e69618171/CT_dataset_pipeline.py#L107
