### ISSUE TITLE
neuroradiologist review of synthetic images

### ISSUE THREAD

**Issue by brandonjnelsonFDA** [bnel1201/PedSilicoICH#72]
raised by Nirmal during the 10/9/2024 research seminar

We can reach out to Dr. Patrick Noonan, a neuro-interventional radiologist who's helped me with a aneurysm device reviews, or Dr. Leroy Williams, a pediatric radiologist

For either of them we'll want to have a collection of our best synthetic cases and a collection of real cases to compare, sampling across our range of lesion, patient, and acquisition variability.

We can discuss whether we want this to be a formal Likert study that we could use in a paper, or informal discussion to focus our development efforts

----
Update 10/29/2024

If accepted to SPR, this is a must

**Comment by brandonjnelsonFDA** [comment]
Part of accomplishing this is first creating a show-and-tell image series (both in dicom and png/ppt format) to show case each lesion type and different dimensions of the synthetic data pipeline (patient, lesion, acquisition characteristics)

We can also feature this on the [sharepoint](https://fda.sharepoint.com/:u:/r/sites/CDRH-OSEL-DIDSR/SitePages/PedSilico-ICH--In-Silico-CT-Imaging-Datasets-for-Pediatric-Device-Assessment-of-Intracranial-Hemorrhage.aspx?csf=1&web=1&e=adxcyl) (we currently have the sample synthetic dataset and summary ppt)

**Comment by jmweaver-FDA** [comment]
The creation of a [presentation for a radiological audience](https://fda.sharepoint.com/:p:/r/sites/CDRH-OSEL-DIDSR/_layouts/15/Doc.aspx?sourcedoc=%7B37BFD6A0-EDD6-4994-9F19-9DC897912ECB%7D&file=[2024-11-20_Show-n-tell.pptx](https://fda.sharepoint.com/:p:/r/sites/CDRH-OSEL-DIDSR/_layouts/15/Doc.aspx?sourcedoc=%7B37BFD6A0-EDD6-4994-9F19-9DC897912ECB%7D&file=2024-11-20_Show-n-tell.pptx&action=edit&mobileredirect=true)&action=edit&mobileredirect=true) is now a top priority due to an upcoming meeting with Dr. Noonan. Will update this issue with summarized feedback following this meeting next week.

**Comment by brandonjnelsonFDA** [comment]
We received good feedback and positive reviews from Dr. Noonan on 11/22/2024 that resulted in new issues #77  and #76 , closing this issue for now.
